const SET_ITEMS = 'SET_ITEMS'
const REQUEST_ITEMS = 'REQUEST_ITEMS'
const SET_PAGINATION = 'SET_PAGINATION'
const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB'
const SET_LOADING = 'SET_LOADING'

export {
  REQUEST_ITEMS,
  SET_ACTIVE_TAB,
  SET_ITEMS,
  SET_LOADING,
  SET_PAGINATION,
}
